### ISSUE TITLE
navigating to other page before tour was shown on page causes tours completeCallback and first tourstep closeAction to be called

### ISSUE THREAD

**Issue by Jerry010** [lsqlabs/ngx-guided-tour#56]
When you navigate to a page where a tour should be shown 
and you navigate away quickly via the menu (in app), both the tour's completeCallback function and the first tourstep's closeAction seem to get called....

**Comment by RobertCMusk** [comment]
Hello @Jerry010 ,
Did you start the tour by calling `startTour` right before the navigation? or maybe a subscription you have that is open is doing it in the background?

If so I think unless you changed the implementation of `ErrorHandler` for angular in your application you should also have an error in the console saying a step there was an error something like:
```
Error: Error finding selector `selector` on step `stepNumber` during guided tour:`tourId`
```
Basically your tour is starting and cannot find the selectors and finishes it self. This is how we currently handle bad selectors; we skip to the next step. And since you are on another page I assume your selectors are no longer valid.

Does this theory match up with what you are seeing?

**Comment by RobertCMusk** [comment]
Closing for now, feel free to reopen with more information!
