### ISSUE TITLE
Guided Tour in Lazy Loaded Modules

### ISSUE THREAD

**Issue by Vbboi24** [lsqlabs/ngx-guided-tour#58]
Hello,

Thanks for this awesome library,

I am trying to add the tour for a lazy loaded module. Unless i add, `<ngx-guided-tour></ngx-guided-tour>` inside lazy-loaded.component.html
The Tour doesnt start. 
I want to create tours on the fly from the backend configuration. Which means, hardcoding the <ngx-guided-tour></ngx-guided-tour> in every component might not look like a good idea. 

Ofcourse, Dynamic Component using component factory is an option. But can you please help me here from a remote config / lazy loaded components?

**Comment by RobertCMusk** [comment]
So `<ngx-guided-tour></ngx-guided-tour>` has to exist as an entry point. I won't know your exact project structure, but it sounds like you want tours to be used across multiple lazy loaded modules so adding it to a common entry element like a `app.component.html` seems to make sense and treating as part of your core lazy loaded module would probably save you a lot of copy and pasting.

We actually lazy load and this is how we add it to our code we have it on our `app.component.html` and pulled into our `app.module.ts` since we want to be able to use it anywhere in the app.

**Comment by RobertCMusk** [comment]
Closing for now, feel free to reopen with more information!
